Deprecate autosiso.bat and autosiso.
These are no longer needed, since autoninja now delegates to either
Ninja or Siso based on the value of the "use_siso" GN arg.

Bug: b/293657720
Change-Id: I612640c6f902b2a1336f856fdf3f723214114ff9

diff --git a/autosiso b/autosiso
--- a/autosiso
+++ b/autosiso
@@ -4,5 +4,9 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-base_dir=$(dirname "$0")
-PYTHONDONTWRITEBYTECODE=1 exec python3 "$base_dir/autosiso.py" "$@"
+echo "Error: 'autosiso' is deprecated and will be removed soon."
+echo ""
+echo "You can just run 'autoninja' instead, which will delegate either to Ninja"
+echo "or to Siso based on the value of the 'use_siso' GN arg in your output folder."
+
+exit 1
