vpython3
Change-Id: I70bc8e7d460f60dcbfa5e141127edecfc2b44744

diff --git a/update_depot_tools b/update_depot_tools
--- a/update_depot_tools
+++ b/update_depot_tools
@@ -100,12 +100,18 @@ function update_git_repo {
   fi
 
   git fetch -q origin &> /dev/null
-  local REBASE_TXT STATUS
+  local CHECKOUT_TXT STATUS
   CHECKOUT_TXT=$(git checkout -q origin/master 2>&1)
   STATUS=$?
   if [[ $STATUS -ne 0 ]]; then
     echo "depot_tools update failed. Conflict in $base_dir" >&2
     echo "$CHECKOUT_TXT" >&2
+  fi
+  CLEAN_TXT=$(git clean -fd -q 2>&1)
+  STATUS=$?
+  if [[ $STATUS -ne 0 ]]; then
+    echo "Warning: Failed to clean untracked files in $base_dir" >&2
+    echo "$CLEAN_TXT" >&2
   fi
   return $STATUS
 }
