Make bots do a force checkout instead of rebase in depot_tools.
There's no case where the bots should have conflicting local changes with
content that's actually committed into the repo.

BUG=673940

Change-Id: Idf970079424dd053dd52258d86bb331beae5820e

diff --git a/update_depot_tools b/update_depot_tools
--- a/update_depot_tools
+++ b/update_depot_tools
@@ -96,15 +96,20 @@ function update_git_repo {
   fi
 
   git fetch -q origin &> /dev/null
-  local REBASE_TXT STATUS
-  REBASE_TXT=$(git rebase -q origin/master 2>&1)
-  STATUS=$?
-  if [[ $STATUS -ne 0 ]]; then
-    echo "depot_tools update failed. Conflict in $base_dir" >&2
-    echo "$REBASE_TXT" >&2
-    git rebase --abort 2> /dev/null
+
+  if [[ "$CHROME_HEADLESS" -eq 1 ]]; then
+    git checkout -f origin/master
+  else
+    local REBASE_TXT STATUS
+    REBASE_TXT=$(git rebase -q origin/master 2>&1)
+    STATUS=$?
+    if [[ $STATUS -ne 0 ]]; then
+      echo "depot_tools update failed. Conflict in $base_dir" >&2
+      echo "$REBASE_TXT" >&2
+      git rebase --abort 2> /dev/null
+    fi
+    return $STATUS
   fi
-  return $STATUS
 }
 
 # Update git checkouts.
